### ISSUE TITLE
Too few arguments

### ISSUE THREAD

**Issue by AraaCuteUwU** [PMMPPluginsRepository/PMExpansion#14]
Error: Too few arguments to function pocketmine\network\mcpe\convert\GlobalItemTypeDictionary::getDictionary(), 0 passed in C:\Users\LENOVO\OneDrive\Documents\project\pm5\plugins\PMExpansion\src\expansion\ItemExpansion.php on line 61 and exactly 1 expected
File: pmsrc/src/network/mcpe/convert/GlobalItemTypeDictionary

**Comment by skh6075** [comment]
I don't support fork
