### ISSUE TITLE
Symfony\Component\Filesystem\Path

### ISSUE THREAD

**Issue by TheLemzz** [PMMPPluginsRepository/PMExpansion#6]
I tried to start my server, but an error occurred.

Error: Class "Symfony\Component\Filesystem\Path" not found
File: plugins/PMExpansion-pm5/src/expansion/ItemExpansion
Line: 73
Type: Error
Backtrace:
#0 plugins/PMExpansion-pm5/src/expansion/ItemExpansion(37): skh6075\pmexpansion\expansion\ItemExpansion::getRuntimeIdByName(string[18] minecraft:ice_bomb)
#1 plugins/PMExpansion-pm5/src/expansion/ItemExpansion(25): skh6075\pmexpansion\expansion\ItemExpansion::register(object skh6075\pmexpansion\item\IceBomb#52086)
#2 plugins/PMExpansion-pm5/src/Loader(29): skh6075\pmexpansion\expansion\ItemExpansion::synchronize()
#3 plugins/PMExpansion-pm5/src/Loader(23): skh6075\pmexpansion\Loader->synchronizeExpansions()
#4 pmsrc/src/plugin/PluginBase(117): skh6075\pmexpansion\Loader->onEnable()
#5 pmsrc/src/plugin/PluginManager(451): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#6 pmsrc/src/Server(1412): pocketmine\plugin\PluginManager->enablePlugin(object skh6075\pmexpansion\Loader#35264)
#7 pmsrc/src/Server(1025): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#35219)
#8 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[10] /root/pm5/, string[18] /root/pm5/plugins/)
#9 pmsrc/src/PocketMine(328): pocketmine\server()
#10 pmsrc(11): require(string[54] phar:///root/pm5/PocketMine-MP.phar/src/PocketMine.php)

**Comment by skh6075** [comment]
Supported from PocketMine-MP software API version 5.0.0 or later
If you cannot find the Symfony\Component\Filesystem\Path class, reinstall PocketMine-MP.
